### ISSUE TITLE
请问如何添加youtube直播监控？

### ISSUE THREAD

**Issue by wjz2001** [voidbean/livewatcher#1]
我看ServerChanMSG是可以监控的，请问这个该如何填写配置文件以开启监控？

**Comment by voidbean** [comment]
这个功能当时没有合并过来, 这两天我抽空加下

**Comment by wjz2001** [comment]
> 这个功能当时没有合并过来, 这两天我抽空加下
非常感谢

**Comment by voidbean** [comment]
该功能已经合并了, 配置文件跟之前的一样, 原来填写b站主播id的地方, 现在也可以填写ytb的channel id了, 会自动识别id是b还是ytb的
